### ISSUE TITLE
Category and Function references in 04b_Backlog.md 

### ISSUE THREAD

**Issue by bradh** [ngageoint/nga-moving-target-indicator-modernization-software#13]
https://github.com/ngageoint/nga-moving-target-indicator-modernization-software/blob/master/04b_Backlog.md has entries like  ` | 11t | Anciliary` that don't seem to related to other parts of the document.

Also it should be "Ancillary".

**Comment by johnscott1000** [comment]
Please disregard the category and function references like those you cited. They are spreadsheet artifacts from a previous SOO iteration and have no meaning in the current format.
