### ISSUE TITLE
Scrub the user stories for consistency and completeness

### ISSUE THREAD

**Issue by bradh** [ngageoint/nga-moving-target-indicator-modernization-software#14]
This needs more work - there are duplicates (e.g. MGUS-541 says "discover and retrieve MTI" and MGUS-569 says "discover MTI data" - same actor, same action) and incomplete requirements (e.g. MGUS-422 says "access MTI data that is standards compliant" which could mean to only access data that is standards compliant, or it could mean that the system has to make non-compliant data into compliant data. At the least it should say what standard the data needs to comply to.)

Some stories have inconsistent rationale (e.g. MGUS-140 says store for the user which is OK, but MGUS-141 says IAW (undeclared) records management policy which is not a user consideration).

**Comment by johnscott1000** [comment]
We are aware of the inconsistencies with the user story backlog and it is being addressed for release of the final RFP. I recommend more focus on the SOO portion as the attached user story backlog is unrefined.
