### ISSUE TITLE
Consider high availability/decentralized objectives and use cases

### ISSUE THREAD

**Issue by robertforbes** [ngageoint/nga-moving-target-indicator-modernization-software#16]
The currently stated objectives and backlog appear to assume only centralized operation where the network always works. Sensors gather data, upload it to a cloud service where it is analyzed and the results disseminated as required. 

This can be hard to scale (the central service gets hammered with data and real time requests) and vulnerable to loss of connectivity between the remote sensors, users and the cloud service. When the network goes down, what do you do? The CAP theorem states that a trade-off is required between data consistency and service availability:

https://en.wikipedia.org/wiki/CAP_theorem

If high availability is the preferred choice, then the data center will need to reconcile the inconsistencies and conflicts that will arise.

Some uses of MTI and track data are obviously time sensitive (where is it now, rather than where was it a few seconds ago). Local service handing can shorten data path lengths and reduce latency.

Some of the smaller UAV platforms lend themselves well to local tactical use. These should continue to work, and a subset of the facilities of the new service should still be available to field users when the cloud link is lost, without reverting to a completely separate user interface.

This can be done through local data aggregation/service provision or "edge computing" as it is often now called working in tandem with the cloud service. However, this is a fundamental choice that will be hard to change later so may be worth some consideration now.

**Comment by johnscott1000** [comment]
This initiative does not address the real time (high availability) streaming MTI capability that is being provided by a different effort. While this capability will ingest and achieve the real time streaming MTI it is not meant to provide real time streaming MTI to users. This capability is to ingest and achieve MTI data (both real time streaming and files) and make the MTI data accessible.
