### ISSUE TITLE
Restrictions on relevant projects too fussy

### ISSUE THREAD

**Issue by robertforbes** [ngageoint/nga-moving-target-indicator-modernization-software#17]
The requirements in sections 8.1.3.3 and 8.1.3.4 of 00_RFP.md seem overly restrictive, not matching normal project reality. 

The criteria are:

1. Must be technically relevant.
2. Must be in the same language as the proposal.
3. Must have had a team of 5-9 people on the job.
4. Must have been done in 6 months.

Few projects that justify a resource profile of 5-9 people will be nicely tidied off within a 6 month period. In addition, technically highly relevant projects would be excluded by having too small a team.

Three examples: the Stanag 4607 library, the 4607 utilities and the cloud based viewer that you have linked to from README.md are all clearly relevant. However, all of these would be disqualified because they were created by a team smaller than 5 people. If they had instead been created less efficiently by a bigger team they would count. Does this really make sense?

I understand that the intent is to demonstrate reasonable sized projects in relevant areas, but this seems needlessly restrictive.

**Comment by johnscott1000** [comment]
We are recommending that the criteria wording be changed from "Must" to "Desire".
