### ISSUE TITLE
Consider providing online, public test tools for data interoperability

### ISSUE THREAD

**Issue by robertforbes** [ngageoint/nga-moving-target-indicator-modernization-software#18]
An online validator could be provided for the various XML and JSON formats used for track data. This would make it easier for third parties to develop equipment that can feed data into NGA's systems. 

This [GeoJSON validator](http://geojsonlint.com/) is an example of what could be done.

**Comment by bradh** [comment]
Track generators would also be useful, but this feels more like things that should come out of the implementation stage (i.e. contract deliverables) than something needed at RFI / proposal time.

**Comment by johnscott1000** [comment]
The team agrees that while this is helpful, it does not need to be part of the RFP. It could be used to differentiate among vendors who recognize the importance and might identified the need in their RFP response.
