### ISSUE TITLE
STANAG 4676 confusion.

### ISSUE THREAD

**Issue by bradh** [ngageoint/nga-moving-target-indicator-modernization-software#2]
00_RFP.md says:

> 3.1.2 STANAG 4676 - Adopt, adapt, or build open services to be exposed or consumed in a cloud-based enterprise for the processing of STANAG 4676 data and data types for the purpose of:
> 
> 3.1.2.1 Ingest: Common vector files (shp, csv, NTRK, KML) - STANAG 4676 in JSON format & edition 1 format - user generated tracks - support discovery & retrieval;

(01_SOO.md says the same, just with different formatting).

That doesn't make sense to me. Are you really trying to parse the format described by STANAG 4676 (i.e. NITS as described in AEDP 12, which is XML), or are you looking to have some general purpose ingest of tracks in various formats:
 - ESRI Shapefile,
 - some CSV (presumably including timestamps and in WGS-84 lat/lon)
 - whatever NTRK is in this context (please consider expanding the acronym or linking to the format description)
 - KML (v2.3, v2.2 with google track extension?)
 - STANAG 4676 Ed 1 (XML)
 - STANAG 4676 Ed 2 when its done (XML, EXI)

What does user generated track mean here? Are you looking to have some kind of UI for the user to create a track by drawing and timestamping it? Or is this "file upload" of one of those formats?

The "support discovery and retrieval" probably isn't an ingest requirement, but rather an indexing requirement (since the discovery and retrieval need is at 3.1.2.3).

**Comment by johnscott1000** [comment]
User-generated tracks refers to manually generated tracks in the 4676 format. In this context the origin of the file is unimportant, the ability to ingest 4676 is the focus.

We anticipate in the final RFP, section 3.1.2.1 will be rewritten to clarify formats for ingest to include STANAG 4676 Ed 1 (XML) and STANAG 4676 Ed 2 (XML, EXI).

**Comment by bradh** [comment]
I note that 4676 Ed 2 may or may not have EXI - likely, but not yet finalised.

> section 3.1.2.1 will be rewritten to clarify formats for ingest to include STANAG 4676 Ed 1 (XML) and STANAG 4676 Ed 2 (XML, EXI).

Does "to include"  mean that the other vector files parts are not required? Or just interesting?

**Comment by johnscott1000** [comment]
4676 Edition 2 is expected to be finalized soon enough to guide any development under this solicitation.
“to include” means the statement does not exclude other vector formats/parts mentioned in the SOO. We strive to make the final RFP free of such ambiguity.
