### ISSUE TITLE
STANAG 4609 / MISB ingest

### ISSUE THREAD

**Issue by bradh** [ngageoint/nga-moving-target-indicator-modernization-software#3]
Is upstream VMTI handling (ingest, index, store, retrieve and display) required? Or is the expectation this will always be converted to STANAG 4676 first?

**Comment by johnscott1000** [comment]
Upstream handling of other formats is not required. We are, for the purpose of ingest, only interested in STANAG 4607 and STANAG 4676 formatted MTI data.
